name: stall_cafe
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  flutter_html_view: ^0.5.11
  flutter_localizations:
    sdk: flutter
  getwidget: ^1.2.2

  cupertino_icons: ^0.1.3
  material_design_icons_flutter: ^4.0.0
  shared_preferences: ">=0.5.12 <2.0.0"
  url_launcher: ^5.4.2
  intl_translation: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

  uses-material-design: true

